from typing import Any, Dict, List, Optional

try:
    from pydantic import BaseModel, Field
except ImportError:
    class BaseModel:
        def __init__(self, **data):
            for k, v in data.items():
                setattr(self, k, v)

    def Field(*args, default=None, default_factory=None, **kwargs):
        if default_factory is not None:
            return default_factory()
        return default


class SearchItemsInput(BaseModel):
    query: str = Field(default="", description="Search term for rental equipment (e.g. 'Alexa', 'Cooke', 'SkyPanel')")
    category: Optional[str] = Field(default=None, description="Optional category filter (e.g. 'Camera Bodies', 'Cinema Lenses', 'Lighting')")


class SearchCustomersInput(BaseModel):
    query: str = Field(default="", description="Customer name, ID, or company to search for")


class CreateCustomerDraftInput(BaseModel):
    name: str = Field(default="", description="Full legal name or production company name")
    email: Optional[str] = Field(default=None, description="Primary billing or contact email")
    phone: Optional[str] = Field(default=None, description="Direct phone number")
    notes: Optional[str] = Field(default=None, description="Context from incoming inquiry")


class ItemAvailabilityRequest(BaseModel):
    item_id: str = Field(default="", description="Rental item code (e.g. 'itm-alexa-35-pkg')")
    quantity: float = Field(default=1.0, description="Quantity requested")


class CheckAvailabilityInput(BaseModel):
    starts_at: str = Field(default="", description="Start timestamp in ISO 8601 format (e.g. '2026-09-01T09:00:00Z')")
    ends_at: str = Field(default="", description="End timestamp in ISO 8601 format (e.g. '2026-09-08T09:00:00Z')")
    items: List[ItemAvailabilityRequest] = Field(default_factory=list, description="List of items with quantities to verify")


class QuoteLineInput(BaseModel):
    item_id: str = Field(default="", description="Item code to quote")
    quantity: float = Field(default=1.0, description="Quantity of units")
    unit_rate: Optional[float] = Field(default=None, description="Daily rate in $ (defaults to catalog rate if omitted)")
    discount_percentage: Optional[float] = Field(default=0.0, description="Discount percentage (0-100)")


class CreateQuoteDraftInput(BaseModel):
    customer_id: str = Field(default="", description="Customer ID or code (e.g. 'cust-dune3-01')")
    starts_at: str = Field(default="", description="Rental period start in ISO 8601")
    ends_at: str = Field(default="", description="Rental period end in ISO 8601")
    lines: List[QuoteLineInput] = Field(default_factory=list, description="Equipment lines included in the quote")
    evidence_ids: Optional[List[str]] = Field(default_factory=list, description="IDs of source evidence (email, pdf upload)")
    notes: Optional[str] = Field(default=None, description="Internal agent notes and rationale")


class SubmitApprovalRequestInput(BaseModel):
    action: str = Field(default="", description="Action identifier (e.g. 'rental.quote.transition_to_reservation')")
    entity_type: str = Field(default="", description="Target DocType (e.g. 'Cortex Rental Transaction', 'Sales Order')")
    entity_id: str = Field(default="", description="Document ID being modified")
    proposed_payload: Optional[Dict[str, Any]] = Field(default=None, description="Proposed document mutations")
    evidence_ids: Optional[List[str]] = Field(default_factory=list, description="Audit evidence references")
    rationale: str = Field(default="", description="Reasoning and summary for human operator review")


class PrepareOwnerStatementInput(BaseModel):
    owner_id: str = Field(default="", description="Consignment owner ID or name")
    gross_amount: float = Field(default=0.0, description="Gross revenue generated by the equipment")
    consignment_percentage: float = Field(default=70.0, description="Owner revenue share percentage")
    serial_no: str = Field(default="", description="Consigned equipment serial number")
    days: float = Field(default=3.0, description="Billable days")
    rate: float = Field(default=1500.0, description="Daily rate")


class GetTransactionInput(BaseModel):
    transaction_id: str = Field(default="", description="Cortex rental transaction ID (e.g. 'CR-TRX-2026-00001')")
